Acme\UserBundle\Entity\Role:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
      user:
        targetEntity: User
        joinColumn:
          role_id:
            referencedColumnName: id
          inverseJoinColumns:
            user_id:
             referencedColumnName: id
        cascade: ["persist"]
    fields:
        name:
            type: string
            length: '255'
            unique: true
        role:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
