security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    encoders:
      Acme\UserV2Bundle\Entity\User:
        algorithm: sha1
        encode_as_base64: false
        iterations: 1 
        
    providers:
        in_memory:
            memory:
               users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        users:
          entity: {class: AcmeUserV2Bundle:user, property:username}
    #encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false
            
        secured_area:
            pattern:    ^/demo/secured/
            #pattern:    /.*
            provider: users              
            form_login:
                #check_path: _security_check
                check_path: login_check
                login_path: login
                remember_me: true
                always_use_default_target_path: false
                default_target_path:            /last_recipes
                target_path_parameter:          _target_path
                use_referer:                    false
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
        user_secured_area:
            pattern:   ^
            anonymous: ~
            provider: users
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /home
        test_secured_area:
            pattern: ^
            provider: users            
            form_login:
                #check_path: _security_check
                check_path: login_check
                login_path: login
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/access_secure, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
