_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

#_demo_secured:
#    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
#    type:     annotation
login:
  path: /login
  defaults: {_controller:AcmeDemoBundle:Secured:login }
login_check:
  path: /login_check 
logout:
    pattern: /logout 

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
    
recipe_name:
    path:      /recipe/
    defaults:  { _controller: AcmeDemoBundle:Recipe:index }
    methods: [GET]
    
new_recipe:
    path:      /admin/new_recipe/
    defaults:  { _controller: AcmeDemoBundle:Recipe:new }
    methods: [GET]
create_recipe:
    path:      /create_recipe/
    defaults:  { _controller: AcmeDemoBundle:Recipe:create }
    methods: [POST]
edit_recipe:
    path:      /edit_recipe/{id}
    defaults:  { _controller: AcmeDemoBundle:Recipe:edit }
    methods: [GET]
update_recipe:
    path:      /update_recipe/{id}
    defaults:  {_controller: AcmeDemoBundle:Recipe:update }
    methods: [PUT]
delete_recipe:
    path:      /delete_recipe/{id}
    defaults:  {_controller: AcmeDemoBundle:Recipe:delete }
    methods: [GET, DELETE]
last_recipes:
    path:      /last_recipes/
    defaults:  {_controller: AcmeDemoBundle:Recipe:lastRecipes }
    methods: [GET]
#login:
#  path: /login
#  defaults: {_controller: AcmeDemoBundle:Security:login}
#login_check:
#  path: /login_check


#Oscar: ruta para mostrar una lista con todos los author
index_author:
    path: /author
    defaults: { _controller: AcmeDemoBundle:Author:index }
    methods: [GET]

#Oscar: ruta para crear el author
create_author:
    path: /author
    defaults: { _controller: AcmeDemoBundle:Author:create }
    methods: [POST]

#Oscar: ruta para crear un author
new_author:
    path: /author/new
    defaults: { _controller: AcmeDemoBundle:Author:new }
    methods: [GET]

#Oscar: ruta para mostrar un author y sus recipes
show_author:
    path: /author/{id}
    defaults: { _controller: AcmeDemoBundle:Author:show }
    methods: [GET]

#Oscar: ruta para editar un author
edit_author:
    path: /author/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Author:edit }
    methods: [GET]

#Oscar: ruta para actuarlizar un author
update_author:
    path: /author/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Author:update }
    methods: [PUT]

#Oscar: ruta para eliminar una author
delete_author:
    path: /author/{id}/delete
    defaults: { _controller: AcmeDemoBundle:Author:delete }
    methods: [GET, DELETE]
