## YAML Template.
Acme\DemoBundle\Entity\Author:
  type: entity
  tables: authors
  oneToMany:
    recipes:
       targetEntity: Recipe
       mappedBy: author
  id: 
    id:
      type: integer
      generator: {strategy : auto}
  fields:
      name:
        type: string
        length: 255
      surname:
        type: string
        length: 255
        

